# Generated by Django 4.2.2 on 2023-07-07 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_ai', '0003_alter_telegramuser_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosePersonage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_ai.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
