# Generated by Django 4.2.2 on 2023-07-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_ai', '0004_choosepersonage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='personage_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='character_ai.character'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChoosePersonage',
        ),
    ]
