# Generated by Django 4.2.2 on 2023-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_ai', '0005_telegramuser_personage_id_delete_choosepersonage'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='welcome_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
