# Generated by Django 4.2.2 on 2023-07-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_ai', '0006_character_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
