# Generated by Django 4.2.2 on 2023-07-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_ai', '0007_telegramuser_telegram_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='personage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='character_ai.character'),
        ),
    ]
